# -*- coding: utf-8 -*-
"""Salary_Projection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JL99y9R_eaIQHwOjHUInY7y9ETIb22XO
"""

import pandas as pd

df = pd.read_csv("Salary_Data.csv")

df.head()

X = df.iloc[:, :-1]
y = df.iloc[:, 1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

import matplotlib.pyplot as plt
plt.scatter(X_train, y_train, color="green")
plt.plot(X_train, regressor.predict(X_train), color="red")
plt.title("Years Experience VS Salary")
plt.xlabel("Years Experience")
plt.ylabel("Salary")
plt.show()

plt.scatter(X_test, y_test, color="green")
plt.plot(X_train, regressor.predict(X_train), color="red")
plt.title("Years Experience VS Salary")
plt.xlabel("Years Experience")
plt.ylabel("Salary")
plt.show()

salary_pred = regressor.predict([[12]])
print("The salary for that amount of years experience is: ", salary_pred)

